#pragma once

#include "esp_event.h"

// Custom event base
ESP_EVENT_DECLARE_BASE(APP_EVENT);

// Custom events
typedef enum {
    APP_EVENT_WIFI_CONNECTED,
    APP_EVENT_WIFI_DISCONNECTED,
    APP_EVENT_MQTT_CONNECTED,
    APP_EVENT_MQTT_DISCONNECTED,
    APP_EVENT_BLE_CONNECTED,
    APP_EVENT_BLE_DISCONNECTED,
    APP_EVENT_SCALE_READY,
    APP_EVENT_SCALE_ERROR,
    APP_EVENT_TARE_REQUEST,
    APP_EVENT_CALIBRATE_REQUEST,
    APP_EVENT_CONFIG_CHANGED,
    APP_EVENT_FACTORY_RESET,
    APP_EVENT_REBOOT,
} app_event_id_t;
