name: esp_scale
description: ESPScale cross-platform app for IoT weighing.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  dio: ^5.4.0
  web_socket_channel: ^3.0.3
  fl_chart: ^1.2.0
  intl: ^0.20.2
  flutter_blue_plus: ^2.3.8
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  windows:
    generate: true
  macos:
    generate: true
    image_path: "assets/icons/app_icon_macos.png"
