#!/usr/bin/env dart
// Reads secrets/app_config.json and generates app/lib/generated/secrets.dart
// Usage: dart scripts/generate_app_secrets.dart
// Run this before `flutter build` or `flutter run` if you have a real API key.

import 'dart:convert';
import 'dart:io';

void main() {
  final secretsFile = File('secrets/app_config.json');
  final outputFile = File('app/lib/generated/secrets.dart');

  String appApiKey = '';
  String mqttUser = '';
  String mqttPass = '';

  if (secretsFile.existsSync()) {
    final json = jsonDecode(secretsFile.readAsStringSync()) as Map<String, dynamic>;
    appApiKey = json['app_api_key'] as String? ?? '';
    mqttUser = json['mqtt_user'] as String? ?? '';
    mqttPass = json['mqtt_pass'] as String? ?? '';
  }

  outputFile.parent.createSync(recursive: true);

  outputFile.writeAsStringSync('''
// AUTO-GENERATED — DO NOT EDIT.
// Generated by scripts/generate_app_secrets.dart from secrets/app_config.json
// If app_api_key is empty, auth is disabled (dev mode).

const String kAppApiKey = '$appApiKey';
const String kMqttUser = '$mqttUser';
const String kMqttPass = '$mqttPass';
''');

  print('Generated ${outputFile.path}');
  print('  app_api_key: ${appApiKey.isEmpty ? "(empty - dev mode)" : "***set***"}');
  print('  mqtt_user:   $mqttUser');
  print('  mqtt_pass:   ${mqttPass.isEmpty ? "(empty)" : "***set***"}');
}